name: Trigger auto deployment for cod-gdal
on:
  push:
    branches: [main]
    paths:
      - "**"
      - ".github/workflows/cod-gdal-AutoDeployTrigger-16d051fb-58c1-4335-b83d-869d9796fc19.yml"
  workflow_dispatch:
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v4
      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.CODGDAL_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.CODGDAL_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.CODGDAL_AZURE_SUBSCRIPTION_ID }}
      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}
          _dockerfilePathKey_: _dockerfilePath_
          registryUrl: fieldmaps.azurecr.io
          registryUsername: ${{ secrets.CODGDAL_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.CODGDAL_REGISTRY_PASSWORD }}
          containerAppName: cod-gdal
          resourceGroup: default
          imageToBuild: fieldmaps.azurecr.io/cod-gdal:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_
